In [1]:
from selenium import webdriver as wd
import urllib
import pandas as pd

In [2]:
driver = wd.Chrome('../tool/chromedriver_76.0.03809.exe')

In [3]:
target_url = 'https://www.naver.com/'

In [4]:
driver.get( target_url )

In [5]:
driver.find_element_by_link_text("네이버뉴스").click()

In [6]:
driver.find_element_by_link_text("정치").click()

In [7]:
from bs4 import BeautifulSoup
import time
from selenium.webdriver.common.keys import Keys
import re

In [15]:
    n = 0
    comments=[]
    names=[]
# for n in range(1,11):
#     a = driver.find_element_by_xpath('//*[@id="right.ranking_contents"]/ul/li[%d]/a'% n) # 가장많이본뉴스 1~10까지 선택
    a = driver.find_element_by_xpath('//*[@id="right.ranking_contents"]/ul/li[%d]/a'% 1)
    a.send_keys(Keys.ENTER)
    b = driver.find_element_by_css_selector('#articleTitleCommentCount') # 댓글보기로 이동
    b.send_keys(Keys.ENTER)
#     driver.find_element_by_tag_name('body').send_keys(Keys.END) # 가장 밑으로 페이지를 내린다
    time.sleep(1)
    try:
        driver.find_element_by_class_name('u_cbox_in_view_comment').click() #댓글 더보기 1 선택
#         time.sleep(0.5)
#         driver.find_element_by_tag_name('body').send_keys(Keys.END) # 가장 밑으로 페이지를 내린다
        while driver.find_element_by_class_name('u_cbox_page_more'):
#             driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
#             time.sleep(3)
            driver.find_element_by_class_name('u_cbox_page_more').click()
#             time.sleep(0.5)
#         driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
    except Exception as e:
        try:
            while driver.find_element_by_class_name('u_cbox_page_more'):
#                 driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
#                 time.sleep(3)
                driver.find_element_by_class_name('u_cbox_page_more').click() # 댓글 더보기 2 선택
            driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
        except Exception as e1:pass


    html = driver.page_source
    dom = BeautifulSoup(html, 'html.parser') # 사람이 볼수있게 변형

    comments_raw = dom.find_all("div",{'class': "u_cbox_text_wrap"}) # 댓글 내용 추출
    nickname_raw = dom.find_all("span",{'class': "u_cbox_nick"}) # 닉네임 추출
    for comment in comments_raw:
        comments.append(comment.text)
    for name in nickname_raw:
        names.append(name.text)

In [161]:
n = 0
comments=[]
names=[]
for n in range(1,11):
    a = driver.find_element_by_xpath('//*[@id="right.ranking_contents"]/ul/li[%d]/a'% n) # 가장많이본뉴스 1~10까지 선택
    a.send_keys(Keys.ENTER)
    b = driver.find_element_by_css_selector('#articleTitleCommentCount') # 댓글보기로 이동
    b.send_keys(Keys.ENTER)
    time.sleep(1)
    try:
        driver.find_element_by_class_name('u_cbox_in_view_comment').click() #댓글 더보기 1 선택
        while driver.find_element_by_class_name('u_cbox_page_more'):
            driver.find_element_by_class_name('u_cbox_page_more').click()
    except Exception as e:
        try:
            while driver.find_element_by_class_name('u_cbox_page_more'):
                driver.find_element_by_class_name('u_cbox_page_more').click() # 댓글 더보기 2 선택
            driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
        except Exception as e1:pass


    html = driver.page_source
    dom = BeautifulSoup(html, 'html.parser') # 사람이 볼수있게 변형

    comments_raw = dom.find_all("div",{'class': "u_cbox_text_wrap"}) # 댓글 내용 추출
    nickname_raw = dom.find_all("span",{'class': "u_cbox_nick"}) # 닉네임 추출
    for comment in comments_raw:
        comments.append(comment.text)
    for name in nickname_raw:
        names.append(name.text)

In [ ]:
n = 0
comments=[]
names=[]
for n in range(1,11):
    a = driver.find_element_by_xpath('//*[@id="right.ranking_contents"]/ul/li[%d]/a'% n) # 가장많이본뉴스 1~10까지 선택
#     a = driver.find_element_by_xpath('//*[@id="right.ranking_contents"]/ul/li[%d]/a'% 10)
    a.send_keys(Keys.ENTER)
    b = driver.find_element_by_css_selector('#articleTitleCommentCount') # 댓글보기로 이동
    b.send_keys(Keys.ENTER)
#     driver.find_element_by_tag_name('body').send_keys(Keys.END) # 가장 밑으로 페이지를 내린다
    time.sleep(1)
    try:
        driver.find_element_by_class_name('u_cbox_in_view_comment').click() #댓글 더보기 1 선택
#         time.sleep(0.5)
#         driver.find_element_by_tag_name('body').send_keys(Keys.END) # 가장 밑으로 페이지를 내린다
        while driver.find_element_by_class_name('u_cbox_page_more'):
#             driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
#             time.sleep(3)
            driver.find_element_by_class_name('u_cbox_page_more').click()
#             time.sleep(0.5)
#         driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
    except Exception as e:
        try:
            while driver.find_element_by_class_name('u_cbox_page_more'):
#                 driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
#                 time.sleep(3)
                driver.find_element_by_class_name('u_cbox_page_more').click() # 댓글 더보기 2 선택
            driver.find_element_by_tag_name('body').send_keys(Keys.END) # 페이지를 가장 밑으로 내린다
        except Exception as e1:pass


    html = driver.page_source
    dom = BeautifulSoup(html, 'html.parser') # 사람이 볼수있게 변형

    comments_raw = dom.find_all("div",{'class': "u_cbox_text_wrap"}) # 댓글 내용 추출
    nickname_raw = dom.find_all("span",{'class': "u_cbox_nick"}) # 닉네임 추출
    for comment in comments_raw:
        comments.append(comment.text)
    for name in nickname_raw:
        names.append(name.text)

In [162]:
df = pd.DataFrame()

In [163]:
df['names'] = names

In [164]:
df['contents'] = comments

In [168]:
len(df)

5159

In [169]:
df

         names                                           contents
0     gulm****                                       조국 힘내서 사퇴하세요
1     khkt****  김성태 재판은 KT사장이 청탁 있었다고 증언나옴.. 조국은 청문회도 안했고...  ...
2     what****  지난 겨울 촛불 집회 외면하다 이럴 때만 선택적 집중을 하는 우리 언론. 어떻게 되...
3     0331****  힘내세요는 전국 전연령이 검색, 사퇴는 특정지역 특정 나이대만 검색.... 국민들의...
4     es01****  힘내세요는 미개한 대깨문들이 지시를 통해 만들었다면 사퇴하세요는 국민들의 자발적 참...
5     wldu****  서울대 연세대 고려대 4만명이상이 부모의 경제력 인맥으로 학종을 발판삼아 합격한 학...
6     myjt****  학생들 전수 조사갑시다. 한명만의 문제가 아니라 입시제도가 문제니 전수조사해서 입학...
7     myth****        이번에 서울대 고대 수준 잘 알았다ㅋㅋㅋㅋㅋㅋㅋㅋㅋ저딴것들이 명문대랍시고ㅋㅋㅋ
8     dbsg****                                            조국 힘내세요
9     ohks****                                   학생들의 촛불집회 지지합니다.
10    cum1****  나라가 이렇게 뒤집어질 정도면 백이면 백 다 사퇴하는데 저렇게  버티는거 보면 사노...
11    puri****  이제서야 말과 행동이 전혀 일치하지 않는 패션 좌파들의 위선과 가식이 청년들 눈에 ...
12    nows****                             학생분들 힘내세요. 지지하고 응원합니다.
13    bird****  먹힌다구?깨졌는데 사퇴하세요는 죄다 수도권 밖에 없더라.힘내세요는 전국.뭘 의미하는...
14    kssc****  조국의 수많은 행적을 보고도 잘했다고 힘내세요하는 국민이 꽤 있다는 것에 절망스럽다...
15    fras****  문빠 섹퀴들아 왜 마스크를 하는지 모르겠냐?  좌파놈들은 자기편 비판하는 사람을 무...
16    mimi****                                 작성자에 의해 삭제된 댓글입니다.
17    smpa****  조국힘내세요의 실체는 어디 있나요? 노조? 전교조? 맘까페? 대체 어디서 흘러나온 ...
18    fras****  좌파는 상대방의 잘못을 지적할 때는 항일투사라도 된듯 미칠듯이 발광하지만 정작 자기...
19    debo****        김경수 두루킹 사건, 버닝썬 사건..문재인 정권 덮고 넘어가려고? 수사안하니?
20    bmwx****  “노(NO) 조국. 시험치지 않습니다. 공부하지 않습니다. 학비 내지 않습니다. 우...
21    appl****  대학생들의 촛불에 민간이들도 합류 할 수 있겠지요?촛불의 의미가 중요하지, 대학생이...
22    hyeo****            연세대도 해라   전국대학 뭐하냐  범법자 조국이 법무장관이 말이되냐?
23    look****  조국이 뭐라고 변명한들 진실은 학생들이 알고있습니다 ! 편법과꼼수로 살아온 사람이 ...
24    7thk****  조국 힘내라고 하는 인간들은 힘내서 더욱 금수저 자식들 무시험으로 직장까지 쭈욱 해...
25    tyu3****                                      고대학생분들 지지합니다!
26    kdh5****  전남대 / 전북대 는  .사라 졌는가 - 양심 과 상식 이 / 너희 대학  특례 입...
27    yhl6****  그동안 드러난 의혹...밝혀진 사실들...근데 후보사퇴를 안하는 못하는 이유가 뭘까...
28    ahah****              우리는  고 노무현대통령님에게  언론이 어떻게했는지 안잊고있습니다.
29    dbss****  뉴스기사 댓글, 실제 밖에선 사퇴하라는 여론이 대다수인데힘내라고?? 전 정부때부터 ...
...        ...                                                ...
5129  koju****  자한당이 보이콧하면 그냥 조국 상대로 쫄았다는거 인증하는 꼴이고, 거기다 윤석열이 ...
5130  jkbk****             검찰수사에 들어가면 모든게 스톱이다. 재판결과를 기다리는게 상식이다.
5131  king****  아니 이놈의 좌파놈들은 지들편이면 뭘해도 옹호를 해주네 조국이 잘한거냐 지금? 조국...
5132  leek****  검찰이 먼저 칼을 들고 선수를 쳐서 청문회 의미없음...조국은 후보 사퇴하고 특검이...
5133  aya1****  국민 여러분 청문회를 열면 통과 못되도 대통령이 자기맘대로 임명강행할수 있는겁니다 ...
5134  ptan****                                 작성자에 의해 삭제된 댓글입니다.
5135  blue****  저것들 신났나보다.. 저기 있는것들 조국보다 더한것들만 쫙 앉아있는데.. 참 양심도 없다
5136  balo****                     청문회가아니라 구속 수사해야하니 유치장에서 해야지 ㅋㅋ
5137  hsle****       조국도 검찰수사하는데...지난,국회난장판 유발 정당은 경찰조사 솔선수범 받아라!
5138  wjss****  청문회 합의 해 놓고 검찰 수사 들어간다니 이젠 보이콧 한다네 자꾸 여론만 살피고 ...
5139  jdku****                 청문회가 의미가 있나? 어차피 임명을 위한 요식 행위일뿐...
5140  auro****  김진태가 주장한 고등학교 입학 특혜는 가짜뉴스로 판명. 청문회하면 가짜뉴스 퍼트린 ...
5141  inar****                          털어도 불법이없으니 어그로 끄네...미친자유당
5142  jkbk****  청문회 할 필요없다. 문재인이가 언제 청문회를 아랑곳 했냐 ? 무조건 임명할께 뻔한...
5143  aodr****  야이  잡것들아  니들은 오로지 조국때리는 일  밖에  없지..?미국 개  자식들이...
5144  dune****  청문회? 제 정신 맞음? 파렴치한 거짖 위선자 데려다 무슨 청문회?? 이 정도 의혹...
5145  jack****  자한당은 의혹만 부풀려놨고 실체가 없으니 청문회해봤자 실익이 없을 테디 제발 보이콧...
5146  ilov****  정치에 아무리 정정당당이 없는 말이긴 하지만 야당이 청문회 열자고 더 푸쉬해야 하는...
5147  enys****  세금이 아깝다. 1. 일안하는 국회의원들 지역구에는 정부지원금도 줄수 없는 법안이 ...
5148  rain****  지들이 청문회 2-3일 해야한대서 말도 안되는 거 받아줬더니 뭔 개소리냐 또?? 그...
5149  suni****                                 작성자에 의해 삭제된 댓글입니다.
5150  thin****  청문회 3일 하자고 떼쓰던게  엊그제 같은데....이제는 보이콧을 한다고???......
5151  stuk****                          사법개혁 검찰개혁의 장애물 통과 과정.....
5152  vy09****  의혹이 청문해로 해명되는게 자명하니 이제 보이콧 정말 질린다제1야당이 이렇게 까지 ...
5153  ecot****  특검하자~만약 한국당이 무책임하게 쏟아낸 의혹들이 거짓으로 판별날 경우 의원직 내려...
5154  daes****  무조건적 반대거부투쟁은  누구를위한것인가  ?       개혁에  여야ㆍ진보수가어디...
5155  inar****                          보이콧 ㅋㅋㅋ 고만꼴갑떨라..ㅈ.이랬다 저랬다
5156  wldh****  도둑질한 놈을 경찰이 조사하는데 경찰 서장 시키려는 꼴.. 이게 나라가 도대체 어떻...
5157  hs-s****  돈많은것은 넘어가지만ㅡ요소요소에불법편법이내재하는한ㆍ교묘히 못되먹은인간이다ㅡ빨리사퇴밖...
5158  dolb****             그래 잘 생각했다 그냥 하지마라 ㅋㅋㅋㅋ 그냥 임명하면 되니께 ㅋㅋㅋ

[5159 rows x 2 columns]

In [170]:
df['cnt'] = df['names'].apply( lambda x: 1 )
df.head(2)

      names                                           contents  cnt
0  gulm****                                       조국 힘내서 사퇴하세요    1
1  khkt****  김성태 재판은 KT사장이 청탁 있었다고 증언나옴.. 조국은 청문회도 안했고...  ...    1

In [171]:
tmp = df

In [172]:
tmp.loc[tmp['names'] == 'ymca****' ]

Empty DataFrame
Columns: [names, contents, cnt]
Index: []

In [173]:
tmp = df.pivot_table( index='names', aggfunc=[sum] )#.loc[['ymca****'], :]

In [174]:
tmp.head(2)

         sum
         cnt
names
007_****   1
007s****   1

In [175]:
tmp.columns=['cnt']

In [176]:
w= tmp.sort_values( by='cnt', ascending=False)

In [177]:
w

          cnt
names
dark****   22
park****   17
blue****   16
youn****   15
good****   14
shin****   13
king****   12
terr****   11
love****   11
drea****   10
hyun****   10
choi****    9
star****    9
whit****    9
kims****    8
happ****    8
kimh****    8
sung****    8
song****    8
yoon****    8
motr****    8
jung****    8
hond****    7
fuck****    7
haha****    7
jeon****    7
nice****    7
dudt****    6
para****    6
post****    6
...       ...
isle****    1
ison****    1
isse****    1
isuc****    1
infa****    1
inav****    1
imsk****    1
imp0****    1
igun****    1
iih1****    1
iiis****    1
iilm****    1
ijin****    1
ijk8****    1
ijl1****    1
ikel****    1
ilj0****    1
ilkw****    1
ilky****    1
ill1****    1
ilsm****    1
ilye****    1
ilyf****    1
im-s****    1
im10****    1
imbl****    1
imda****    1
imdd****    1
imjj****    1
zzuk****    1

[3726 rows x 1 columns]

In [160]:
if w.apply > 2  :
    a =w['cnt']

TypeError: '>' not supported between instances of 'method' and 'int'

In [149]:
if a == 'True' :

TypeError: invalid type comparison

In [117]:
tmp.loc[tmp['names'] == '%d' ], %n

SyntaxError: invalid syntax (<ipython-input-117-a0a53278749d>, line 1)

In [62]:
df.set_index(['names']).count()

contents    360
dtype: int64

In [ ]:
for n in  :
    df[ df['names'].apply( lambda x : x.find('%d')==0 ), % n ]

In [55]:
df[ df['names'].apply( lambda x : x.find('ymca')==0 ) ]

        names                                           contents
22   ymca****  우리나라 최강 기업이 5조가 없어서 그 동안 안만들었겠음?문재인의 대응책이라곤 북한...
214  ymca****  하이닉스 삼성이 반도체 최강국을 만들어주니까 몇몇 정치인들이 우리나라가 ㅈㄴ탐스럽나...
256  ymca****  하이닉스나 삼성이 반도체 최강국을 만들어주니까 몇몇 정치인들이 우리나라가 ㅈㄴ탐스럽...

In [53]:
a,len(a)

(array(['hane****', 'love****', 'cool****', 'hujo****', 'kgim****',
        'rhdd****', 'coff****', '3hjw****', 'burn****', 'sher****',
        'hssj****', 'wkd1****', 'junh****', 'alcl****', 'sati****',
        'apex****', 'amej****', 'jwoo****', 'naso****', 'pani****',
        'berr****', 'jyp8****', 'ymca****', 'ckg1****', 'atti****',
        'glwl****', 'nhsm****', 'byun****', 'kisk****', 'stju****',
        'yonw****', 'lege****', 'enjo****', 'woot****', 'gunn****',
        'kcy3****', 'hiso****', 'hwji****', 'adon****', 'cjdg****',
        'gu79****', 'bloc****', 'jeny****', 'acoj****', '901w****',
        'kimj****', 'euni****', 'ssdt****', 'bea2****', 'xoqj****',
        'payo****', 's798****', 'news****', 'gmrx****', 'ans2****',
        'jung****', 'jbj5****', 'blue****', '1124****', 'lake****',
        'terr****', 'seun****', 'yim9****', 'kata****', 'lji9****',
        'tery****', 'rapg****', 'duu7****', 'kmid****', 'asag****',
        'sizi****', 'hell****', 'give****', 'supe****', 'back****',
        'wjyo****', 'yeoi****', 'cky9****', 'ptbb****', 'jinj****',
        'vics****', 'yong****', 'fair****', 'wjda****', 'jun9****',
        'joon****', 'ip_f****', 'luj9****', 'ukh7****', 'jspk****',
        'refr****', 'whff****', '5535****', 'fran****', 'wing****',
        'ky92****', 'stra****', 'naog****', 'hees****', 'jinn****',
        'dhki****', 'ckdg****', 'jjpm****', 'syst****', 'gnsl****',
        'juca****', 'jofi****', 'cndl****', 'kwan****', 'tanu****',
        'swt1****', 'ihop****', 'king****', 'csk5****', 'amig****',
        'rcha****', 'hkki****', 'buzb****', 'manc****', 'sbs6****',
        'chan****', 'dmz5****', 'taex****', 'taki****', 'drjo****',
        'el_m****', 'dkk2****', 'jukj****', 'jsol****', 'midy****',
        'sddy****', 'sunn****', 'bfdn****', 'wsn4****', 'stro****',
        'fmnu****', 'lhju****', 'deux****', 'kwon****', 'blac****',
        'poor****', 'sohk****', 'wkdr****', 'k484****', 'ajm6****',
        'sawa****', 'tink****', 'gagu****', 'mora****', 'unit****',
        'puff****', 'jhjn****', 'j844****', 'stea****', 'firs****',
        'serb****', 'kimb****', 'memo****', 'swch****', 'kor1****',
        'usur****', 'jeon****', 'bran****', 'noby****', 'enti****',
        'star****', 'ilov****', 'suan****', 'wjdw****', 'ktr1****',
        'qkdr****', 'gara****', 'sjyl****', 'wa13****', 'gunc****',
        'hana****', 'hwan****', 'lky3****', 'merr****', 'odmp****',
        'ddll****', 'tryt****', 'ocn1****', 'kuk0****', 'free****',
        'jsyu****', 'kimd****', 'sera****', 'kkyj****', 'csc5****',
        'chic****', '7077****', 'intt****', 'chal****', 'hope****',
        'davi****', 'mini****', 'kjcc****', 'dlau****', 'lenn****',
        'kchs****', 'aseh****', 'kims****', 'hcp8****', 'ghkn****',
        'gucc****', 'wonj****', 'hiph****', 'hong****', 'taek****',
        'yhs6****', 'nice****', 'hgd2****', 'hce0****', 'cid9****',
        'beck****', 'son8****', 'gore****', 'seri****', 'chun****',
        'band****', 'shar****', 'brig****', 'sang****', 'akzk****',
        'jaeb****', 'elvi****', 'abcd****', '7thk****', 'pjij****',
        'doto****', 'com2****', 'kym9****', 'appl****', 'dark****',
        'hjkm****', 'bodo****', 'y5k5****', '0ja2****', 'gide****',
        'ukmj****', 'gtha****', 'zook****', 'song****', 'wsy0****',
        'bcpa****', 'tkqh****', 'kwj8****', 'mss0****', 'ekfv****',
        'bari****', 'drag****', 'dyd3****', 'mmca****', 'pass****',
        'deic****', 'amet****', 'qlcd****', 'newf****', 'mira****',
        'leez****', 'wbel****', 'kizm****', 'kora****', 'gily****',
        'dlcj****', 'spir****', 'ficl****', 'zamm****', 'shoo****',
        'nunk****', 'mong****', 'sin3****', 'duo2****', 'croc****',
        'cjsw****', 'csy4****', 'jhch****', 'asto****', 'park****',
        'sohh****', '0181****', 'kgb3****', 'tjqc****', 'pip7****',
        '3701****', 'kjk0****', 'zimz****', 'forz****', 'whdr****',
        'ckoh****', 'noye****', 'kns3****', 'jhy1****', 'smsm****',
        'tedd****', 'kurf****', 'milp****', 'qkrd****', 'milj****',
        'pcm2****', 'ansa****', 'csun****', 'hhs2****', 'rufs****',
        'khle****', 'khs0****', 'myca****', 'good****', 'jich****',
        'okoo****', 'just****', 'rein****', 'niln****', 'boob****',
        'efg0****', '84wi****', 'yg24****', 'mrnb****', 'cctv****',
        'open****', 'kumh****', 'wwwa****', 'june****', 'wjdt****',
        'e_ha****', 'oxox****', 'wjdq****', 'soks****', 'nana****'],
       dtype=object), 330)

In [45]:
if tmp != a :

ValueError: Lengths must match to compare

In [27]:
tmp = df.contents

In [28]:
len(tmp.unique())

342

In [ ]:
# import time
# for n in range(1,11):
#     a = driver.find_element_by_xpath('//*[@id="right.ranking_contents"]/ul/li[%d]/a'% n) 
#     a.click()
#     b = driver.find_element_by_css_selector('#articleTitleCommentCount > span.lo_txt')
#     b.click()
#     time.sleep(5)

In [ ]:
# link = []
# title = []
# for n in driver.find_elements_by_css_selector('div.aside > div > div#ranking_100 > ul > li > a'):
#     link.append(n.get_attribute('href'))
#     title.append(n.get_attribute('title'))

In [ ]:
# for i in a:
#     print(i)

In [ ]:
# for n in driver.find_elements_by_css_selector('#ranking_100 > ul > li > a'):
#     print(n)

In [ ]:
# for n in driver.find_elements_by_xpath('//*[@id="ranking_100"]/ul/li[1]/a'):
#     print(n)

In [ ]:
# for n in driver.find_elements_by_css_selector('#right\.ranking_contents'):
#     print(n)