In [1]:
# 아까는 데이터를 모두 모아서 하니 에러가 계속났다
# 그래서 4대 질병 데이터를 각각 월 합산, 월평균을 내고
# 그것을 지역별로 모은다
#                지역구
#          감기   천식  
# 14년1월

In [178]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import re

In [464]:
# 감기
cold_sigun=pd.read_csv('./data/realdiz/cold_sigun.csv', encoding = 'euc-kr')
# 칼럼명 변경
cold_sigun.rename(columns={'발생건수(건)':'감기 발생건수'}, inplace = True)
#1401 ~ 1812 까지 만들기 
#201412= 20141231/100
tmp_m = []
for n in range(len(cold_sigun)):
    tmp_m.append(cold_sigun['날짜'][n]//100)
#날짜/ 시군구지역코드/ 감기 발생건수/ 월별
cold_sigun['월별']=tmp_m
#월별만 모으기
cold_m=cold_sigun.drop('날짜',1)
#날짜만 모으기
cold_d=cold_sigun.drop('월별',1)
#월별 지역구별  감기발생건수 합과 평균
cold_m_piv=cold_m.pivot_table(index='월별', columns='시군구지역코드', aggfunc = np.sum)
cold_m_piv

         감기 발생건수                                                           \
시군구지역코드    11110    11140    11170    11200     11215     11230     11260
월별
201401   31655.0  29272.0  50641.0  73202.0   86296.0   84582.0   99756.0
201402   35942.0  33873.0  55249.0  85885.0  102934.0  101553.0  122671.0
201403   30333.0  28057.0  49126.0  72180.0   87582.0   82540.0  101098.0
201404   30378.0  28550.0  49942.0  74699.0   86321.0   83626.0   98450.0
201405   26261.0  23864.0  41657.0  61023.0   70632.0   68143.0   81472.0
201406   18915.0  18463.0  32175.0  46492.0   54328.0   52053.0   61810.0
201407   19618.0  18618.0  31454.0  46878.0   54200.0   52441.0   61314.0
201408   17069.0  16570.0  28841.0  40580.0   48408.0   46177.0   57552.0
201409   23804.0  21846.0  37822.0  54769.0   65516.0   62917.0   78124.0
201410   28227.0  26111.0  45414.0  66679.0   81279.0   77212.0   94927.0
201411   31224.0  29388.0  49665.0  74109.0   90146.0   86383.0  104688.0
201412   29745.0  27688.0  49001.0  70705.0   84661.0   83873.0   99512.0
201501   27492.0  26589.0  43044.0  64244.0   77687.0   76864.0   90516.0
201502   27420.0  25892.0  42272.0  64393.0   79863.0   77446.0   90360.0
201503   31558.0  29420.0  49353.0  72146.0   88255.0   86133.0  103772.0
201504   30834.0  28471.0  48565.0  70150.0   85878.0   83741.0   96753.0
201505   24305.0  22778.0  38797.0  56782.0   68189.0   65112.0   78792.0
201506   17703.0  16383.0  27432.0  38825.0   47917.0   48576.0   57586.0
201507   12427.0  12198.0  21076.0  31481.0   36285.0   37152.0   44399.0
201508   15465.0  13971.0  25694.0  37054.0   43945.0   41879.0   51883.0
201509   23412.0  21324.0  39438.0  55540.0   67569.0   63815.0   78288.0
201510   24977.0  22970.0  40703.0  58081.0   70505.0   67674.0   83672.0
201511   27137.0  24629.0  42778.0  63279.0   75932.0   73956.0   92054.0
201512   30661.0  28785.0  49148.0  72001.0   86920.0   85958.0  107212.0
201601   27149.0  24576.0  42282.0  60896.0   75677.0   74231.0   94969.0
201602   29940.0  29005.0  47512.0  71066.0   88420.0   86288.0  107294.0
201603   31397.0  28793.0  48782.0  72360.0   87493.0   84937.0  107223.0
201604   29406.0  26296.0  46891.0  68330.0   84433.0   80505.0   99624.0
201605   25048.0  22646.0  39953.0  58989.0   70650.0   67963.0   82025.0
201606   19132.0  17835.0  32250.0  46893.0   53917.0   53267.0   64164.0
201607   17497.0  15928.0  28390.0  41221.0   48346.0   48140.0   60014.0
201608   15858.0  14846.0  26461.0  37681.0   44705.0   43380.0   54937.0
201609   20035.0  19244.0  33422.0  48257.0   58045.0   54849.0   69094.0
201610   24107.0  23529.0  40130.0  58750.0   69862.0   67079.0   84585.0
201611   27339.0  26786.0  45514.0  66488.0   80923.0   77651.0   96064.0
201612   40854.0  38311.0  65753.0  94229.0  117641.0  110474.0  140745.0
201701   25040.0  24776.0  38422.0  58083.0   72625.0   68682.0   86704.0
201702   20775.0  20650.0  33805.0  51490.0   64844.0   61605.0   75442.0
201703   27906.0  27014.0  45379.0  68818.0   80554.0   79044.0   94180.0
201704   29203.0  27314.0  46917.0  72379.0   84596.0   80829.0   97774.0
201705   23939.0  22155.0  38480.0  59086.0   68531.0   63817.0   79245.0
201706   19484.0  18674.0  31073.0  47654.0   54482.0   52087.0   63033.0
201707   16851.0  15800.0  27365.0  41887.0   46459.0   46099.0   55153.0
201708   17225.0  15876.0  27018.0  41409.0   47049.0   43482.0   55322.0
201709   24626.0  23066.0  37720.0  59962.0   68519.0   62459.0   76421.0
201710   20979.0  19382.0  32532.0  50112.0   59446.0   54982.0   69548.0
201711   28477.0  27015.0  44583.0  70951.0   81356.0   79776.0   94421.0
201712   35046.0  33390.0  54282.0  83288.0   97844.0   95247.0  113207.0
201801   35800.0  34055.0  53626.0  81849.0   98063.0   92875.0  115867.0
201802   20727.0  20449.0  32328.0  49715.0   60909.0   56898.0   70200.0
201803   23366.0  22572.0  38659.0  59341.0   71384.0   66194.0   80859.0
201804   26929.0  26636.0  43617.0  68890.0   79855.0   72468.0   88328.0
201805   24664.0  25317.0  38910.0  63386.0   70294.0   65111.0   76247.0
201806   18810.0  18951.0  30898.0  49448.0   53179.0   49630.0   60208.0

                                       ...                              \
시군구지역코드     11290     11305     11320  ...     48840    48850    48860
월별                                     ...
201401   108965.0   72394.0   78931.0  ...   11184.0  10935.0   7974.0
201402   130996.0   88973.0   96236.0  ...   12417.0  13195.0   8210.0
201403   108883.0   71768.0   78729.0  ...   11179.0  10645.0   7091.0
201404   108963.0   73427.0   77854.0  ...   10176.0   9448.0   6277.0
201405    91799.0   60836.0   66698.0  ...    8725.0   7787.0   5458.0
201406    69346.0   46236.0   49085.0  ...    5308.0   5437.0   3640.0
201407    70996.0   48421.0   49855.0  ...    5156.0   5294.0   3299.0
201408    61322.0   42252.0   46425.0  ...    4644.0   4899.0   3088.0
201409    82492.0   56832.0   64185.0  ...    7267.0   6777.0   4406.0
201410   100256.0   69597.0   76045.0  ...    7952.0   7790.0   5533.0
201411   109987.0   75743.0   85758.0  ...   10636.0   9464.0   6447.0
201412   106910.0   73808.0   81111.0  ...   12213.0  10953.0   8049.0
201501    94636.0   67848.0   73176.0  ...   12655.0  10409.0   7508.0
201502    96491.0   69688.0   75468.0  ...   12957.0  11712.0   8616.0
201503   110299.0   77210.0   84431.0  ...   11916.0  12151.0   8639.0
201504   106637.0   72903.0   81950.0  ...   11238.0  10603.0   7050.0
201505    84883.0   58373.0   63705.0  ...    9884.0   8821.0   6723.0
201506    63478.0   45014.0   47466.0  ...    8440.0   7174.0   4735.0
201507    48409.0   34898.0   34702.0  ...    4984.0   4679.0   3158.0
201508    54748.0   39694.0   42579.0  ...    4821.0   4625.0   3319.0
201509    84583.0   60116.0   65072.0  ...    6661.0   6934.0   4756.0
201510    86613.0   62576.0   68248.0  ...    9039.0   8893.0   6437.0
201511    92743.0   67122.0   73323.0  ...    9506.0   9060.0   6037.0
201512   109048.0   80565.0   85765.0  ...   11386.0  11816.0   7592.0
201601    92606.0   68928.0   75008.0  ...   12112.0  11937.0   8222.0
201602   105303.0   77926.0   82778.0  ...   12652.0  12594.0   8980.0
201603   107557.0   78251.0   85934.0  ...   10663.0  10077.0   7369.0
201604   104203.0   72637.0   82387.0  ...    8981.0   8796.0   6628.0
201605    88148.0   60967.0   68415.0  ...    7912.0   7713.0   5868.0
201606    67775.0   48897.0   52645.0  ...    6087.0   5821.0   4017.0
201607    62211.0   44453.0   47350.0  ...    5005.0   4684.0   3453.0
201608    57239.0   39850.0   44815.0  ...    4992.0   5046.0   3330.0
201609    72726.0   51131.0   56926.0  ...    6492.0   6149.0   4587.0
201610    87614.0   62330.0   69031.0  ...    8156.0   8423.0   6276.0
201611   103194.0   72070.0   81568.0  ...   10267.0   9500.0   7069.0
201612   146812.0  105355.0  114738.0  ...   12182.0  12609.0   8749.0
201701    88372.0   63851.0   70507.0  ...   10866.0  11606.0   7614.0
201702    75412.0   54566.0   60069.0  ...    8972.0   8866.0   6302.0
201703    98231.0   71019.0   77904.0  ...   10112.0   9872.0   6624.0
201704   103701.0   72696.0   78083.0  ...   10993.0  10084.0   7044.0
201705    84396.0   58343.0   63485.0  ...    8456.0   8231.0   6486.0
201706    68767.0   47390.0   52155.0  ...    5867.0   5967.0   4557.0
201707    60614.0   40412.0   44741.0  ...    5002.0   4937.0   4048.0
201708    61527.0   40968.0   45916.0  ...    4526.0   4511.0   3560.0
201709    86842.0   56682.0   66275.0  ...    6096.0   6022.0   4585.0
201710    70898.0   50865.0   56926.0  ...    6947.0   6866.0   4973.0
201711    98791.0   68843.0   79471.0  ...    9871.0   9615.0   6482.0
201712   119353.0   84999.0   94092.0  ...   12761.0  13082.0   9412.0
201801   117773.0   87100.0   96996.0  ...   16128.0  14823.0  12343.0
201802    72019.0   51415.0   57867.0  ...    9825.0   9594.0   6757.0
201803    83351.0   58018.0   67536.0  ...    8707.0   8066.0   6057.0
201804    95391.0   66818.0   75224.0  ...    8648.0   8154.0   6617.0
201805    85973.0   59180.0   66365.0  ...    8529.0   7905.0   5870.0
201806    66427.0   44699.0   50627.0  ...    6228.0   5771.0   4418.0


시군구지역코드    48870    48880    48890     49110    49130 49710 49720
월별
201401   12818.0  16069.0  12872.0  120914.0  53792.0  59.0  61.0
201402   14468.0  20085.0  14827.0  119568.0  49094.0  87.0  60.0
201403   11511.0  15197.0  12835.0  112276.0  45968.0  62.0  49.0
201404    9862.0  14171.0  10853.0  109286.0  40890.0  72.0  85.0
201405    9317.0  11156.0   8879.0   97305.0  37236.0  58.0  69.0
201406    6619.0   8006.0   6087.0   71923.0  27973.0  56.0  47.0
201407    5616.0   7123.0   5234.0   68696.0  24158.0  30.0  39.0
201408    5130.0   6169.0   5089.0   68095.0  23305.0  32.0  30.0
201409    7309.0   9795.0   7701.0   86297.0  31713.0  55.0  57.0
201410    9272.0  11532.0   9461.0  100773.0  37701.0  44.0  58.0
201411   10376.0  14297.0  10739.0  122888.0  43854.0  60.0  64.0
201412   11955.0  15169.0  13438.0  131666.0  46622.0  98.0  60.0
201501   10885.0  12624.0  11815.0  111515.0  42181.0   NaN   NaN
201502   14503.0  13686.0  11964.0  109190.0  39655.0   NaN   NaN
201503   16205.0  19866.0  15201.0  144150.0  56184.0   NaN   NaN
201504   12736.0  14837.0  11745.0  134486.0  49197.0   NaN   NaN
201505   10657.0  12007.0   9781.0  102003.0  39049.0   NaN   NaN
201506    7391.0   9222.0   7935.0   76738.0  29752.0   NaN   NaN
201507    5100.0   6653.0   5449.0   54072.0  21461.0   NaN   NaN
201508    4867.0   6185.0   5056.0   59772.0  23431.0   NaN   NaN
201509    7090.0   9306.0   7482.0   89163.0  31702.0   NaN   NaN
201510    9326.0  11747.0   9852.0  104132.0  39377.0   NaN   NaN
201511    9137.0  12441.0   9304.0  101488.0  39384.0   NaN   NaN
201512   11159.0  13947.0  12192.0  121163.0  47305.0   NaN   NaN
201601   10244.0  14411.0  13056.0  105768.0  44213.0   NaN   NaN
201602   12111.0  16138.0  14700.0  115177.0  46875.0   NaN   NaN
201603   11410.0  14758.0  11491.0  134394.0  50144.0   NaN   NaN
201604    9332.0  12294.0   9925.0  107500.0  39602.0   NaN   NaN
201605    7653.0  10413.0   8787.0   99573.0  37892.0   NaN   NaN
201606    5390.0   7615.0   6733.0   79362.0  31981.0   NaN   NaN
201607    5013.0   6535.0   5281.0   64648.0  25455.0   NaN   NaN
201608    4273.0   6521.0   5646.0   64757.0  25685.0   NaN   NaN
201609    6455.0   9485.0   7620.0   76205.0  28779.0   NaN   NaN
201610    7892.0  11197.0   9711.0   97263.0  35531.0   NaN   NaN
201611    7816.0  11676.0  10230.0  110544.0  42147.0   NaN   NaN
201612   10034.0  18307.0  13580.0  148053.0  52948.0   NaN   NaN
201701    9242.0  14203.0  12699.0  111377.0  47547.0   NaN   NaN
201702    7430.0  11328.0  10029.0   85451.0  36477.0   NaN   NaN
201703    8244.0  12948.0  10784.0  115453.0  46413.0   NaN   NaN
201704    8840.0  13303.0  11082.0  113535.0  43948.0   NaN   NaN
201705    7830.0  11927.0   9468.0   99751.0  40880.0   NaN   NaN
201706    5416.0   8947.0   6125.0   78603.0  30894.0   NaN   NaN
201707    4431.0   7338.0   5038.0   64372.0  23701.0   NaN   NaN
201708    4654.0   6780.0   5393.0   63487.0  25922.0   NaN   NaN
201709    6022.0   9786.0   6716.0   80850.0  31744.0   NaN   NaN
201710    6192.0  10163.0   7202.0   85810.0  33678.0   NaN   NaN
201711    7798.0  13746.0   9523.0  115712.0  44762.0   NaN   NaN
201712    9968.0  17315.0  13853.0  136839.0  52690.0   NaN   NaN
201801   12125.0  22912.0  16635.0  138404.0  63090.0   NaN   NaN
201802    7812.0  13561.0   9496.0   83451.0  37422.0   NaN   NaN
201803    6900.0  11773.0   8678.0  108997.0  42923.0   NaN   NaN
201804    7218.0  12052.0   8678.0  111076.0  43264.0   NaN   NaN
201805    6618.0  10674.0   8297.0  101863.0  42817.0   NaN   NaN
201806    4890.0   8249.0   5952.0   79111.0  32328.0   NaN   NaN

[54 rows x 257 columns]

In [314]:
# 천식
breath_sigun=pd.read_csv('./data/realdiz/breath_sigun.csv', encoding = 'euc-kr')
breath_sigun.rename(columns={'발생건수(건)':'천식 발생건수'}, inplace = True)
tmp_m = []
for n in range(len(breath_sigun)):
    tmp_m.append(breath_sigun['날짜'][n]//100)
breath_sigun['월별']=tmp_m
breath_m=breath_sigun.drop('날짜',1)
breath_d=breath_sigun.drop('월별',1)
breath_m_piv=breath_m.pivot_table(index='월별', columns='시군구지역코드', aggfunc = [np.sum, np.mean])
breath_m_piv

            sum                                                             \
        천식 발생건수
시군구지역코드   11110   11140   11170   11200    11215   11230    11260    11290
월별
201401   2113.0  2657.0  3342.0  4636.0   8174.0  5677.0   8691.0   9742.0
201402   2194.0  3153.0  3434.0  4840.0   8955.0  6620.0   9852.0  10998.0
201403   2012.0  3015.0  3580.0  4663.0   9076.0  6354.0   9550.0   9618.0
201404   2229.0  3830.0  3865.0  5467.0   9490.0  7327.0  10042.0  10795.0
201405   2146.0  3005.0  3461.0  4714.0   7921.0  5957.0   8772.0   9878.0
201406   1531.0  2354.0  2617.0  3642.0   6151.0  4484.0   6271.0   6969.0
201407   1482.0  2089.0  2488.0  3947.0   5759.0  4411.0   5648.0   6804.0
201408   1395.0  1895.0  2383.0  3355.0   5137.0  3957.0   5308.0   6133.0
201409   1740.0  2546.0  3117.0  4521.0   7050.0  5428.0   7101.0   7854.0
201410   1958.0  2830.0  3558.0  5199.0   8446.0  6325.0   8267.0   9130.0
201411   2131.0  3189.0  3848.0  5637.0   9194.0  7249.0   8956.0   9514.0
201412   2219.0  3083.0  4050.0  5766.0   8955.0  6915.0   8906.0  10565.0
201501   2031.0  2672.0  3249.0  4970.0   7668.0  5951.0   8059.0   8083.0
201502   1951.0  2291.0  3202.0  4740.0   7802.0  5700.0   7382.0   7614.0
201503   2190.0  2614.0  3445.0  5435.0   8087.0  6586.0   8331.0   8565.0
201504   2243.0  2587.0  3752.0  5597.0   8699.0  6755.0   7980.0   8911.0
201505   1858.0  2023.0  3170.0  4561.0   7560.0  6052.0   7611.0   7872.0
201506   1296.0  1555.0  2338.0  3360.0   4747.0  4082.0   5791.0   5284.0
201507   1127.0  1282.0  1969.0  3182.0   4102.0  3509.0   5129.0   4499.0
201508   1318.0  1347.0  2315.0  3685.0   4701.0  3886.0   5645.0   5044.0
201509   1684.0  1978.0  3006.0  4678.0   6849.0  5047.0   7263.0   6539.0
201510   1678.0  2198.0  3314.0  5210.0   7909.0  5352.0   7687.0   7155.0
201511   1726.0  2323.0  3278.0  6026.0   7970.0  5668.0   8382.0   7044.0
201512   1861.0  2983.0  4235.0  6469.0   9659.0  7182.0  10191.0   9265.0
201601   1652.0  2133.0  3432.0  5118.0   7713.0  5782.0   8602.0   7198.0
201602   1786.0  2163.0  3141.0  5577.0   8453.0  6454.0   8651.0   7282.0
201603   1861.0  2401.0  3695.0  6081.0   8552.0  6448.0   9024.0   7290.0
201604   1925.0  2380.0  3475.0  6035.0   8820.0  6257.0   9096.0   7263.0
201605   1818.0  2306.0  3317.0  4891.0   8061.0  5550.0   8280.0   6533.0
201606   1259.0  1611.0  2510.0  3922.0   5561.0  4296.0   6305.0   5155.0
201607   1149.0  1300.0  2266.0  3266.0   5112.0  3764.0   5438.0   4518.0
201608   1189.0  1301.0  2194.0  3266.0   4580.0  3609.0   5228.0   4277.0
201609   1475.0  1746.0  2827.0  4368.0   6207.0  4514.0   6530.0   5179.0
201610   1552.0  2113.0  3239.0  5380.0   7309.0  5493.0   7544.0   6211.0
201611   1913.0  2545.0  3681.0  6263.0   8668.0  6358.0   8748.0   7054.0
201612   2467.0  2916.0  4328.0  7902.0  11708.0  8451.0  10347.0   8883.0
201701   1780.0  2267.0  2980.0  4969.0   7562.0  5418.0   7315.0   5984.0
201702   1335.0  1860.0  2844.0  4305.0   6910.0  4804.0   6587.0   5290.0
201703   1755.0  2252.0  3478.0  5671.0   8435.0  6070.0   7945.0   6271.0
201704   1743.0  2120.0  3594.0  5911.0   8834.0  6293.0   8143.0   6639.0
201705   1612.0  1919.0  3205.0  5024.0   7324.0  5220.0   7546.0   5895.0
201706   1278.0  1658.0  2630.0  3886.0   5808.0  4275.0   5641.0   4784.0
201707   1118.0  1241.0  2275.0  3550.0   4707.0  3715.0   5093.0   4122.0
201708   1265.0  1253.0  2143.0  3264.0   4415.0  3387.0   4853.0   3985.0
201709   1521.0  1605.0  2911.0  4373.0   6496.0  4569.0   6071.0   5239.0
201710   1311.0  1557.0  2501.0  3872.0   6051.0  4430.0   5846.0   4606.0
201711   1622.0  2108.0  3355.0  5440.0   8266.0  6291.0   8053.0   6338.0
201712   1855.0  2367.0  3462.0  5612.0   9460.0  7019.0   8987.0   7302.0
201801   2055.0  2463.0  3312.0  5187.0   8122.0  6415.0   8031.0   6971.0
201802   1399.0  1721.0  2264.0  3642.0   5261.0  4781.0   5711.0   5039.0
201803   1456.0  2065.0  2754.0  4149.0   5821.0  5322.0   6832.0   5380.0
201804   1698.0  2471.0  3109.0  4975.0   6518.0  5733.0   7386.0   6284.0
201805   1612.0  2041.0  2995.0  4947.0   5885.0  5525.0   6581.0   5849.0
201806   1240.0  1546.0  2300.0  3711.0   4403.0  4355.0   5262.0   4620.0

                            ...          mean                        \
                            ...       천식 발생건수
시군구지역코드    11305   11320    ...         48840      48850      48860
월별                          ...
201401    9074.0  7843.0    ...     65.258065  42.806452  17.870968
201402   11253.0  8519.0    ...     72.392857  50.892857  20.000000
201403    9344.0  7842.0    ...     66.096774  41.709677  15.677419
201404    9989.0  8520.0    ...     65.766667  40.266667  20.000000
201405    8671.0  7594.0    ...     57.806452  37.548387  18.258065
201406    6345.0  5652.0    ...     42.233333  31.600000  14.833333
201407    6329.0  5823.0    ...     41.290323  29.064516  13.967742
201408    5679.0  5125.0    ...     41.225806  27.580645  14.451613
201409    7061.0  6384.0    ...     50.933333  35.100000  15.633333
201410    8131.0  7249.0    ...     50.225806  32.322581  15.548387
201411    8099.0  7753.0    ...     60.833333  33.800000  17.066667
201412    8964.0  7997.0    ...     61.548387  39.225806  17.709677
201501    8077.0  7043.0    ...     65.225806  37.838710  16.548387
201502    8294.0  6604.0    ...     71.321429  45.321429  19.642857
201503    8943.0  7177.0    ...     64.419355  45.258065  21.032258
201504    8436.0  7437.0    ...     69.466667  43.700000  20.766667
201505    7190.0  6226.0    ...     61.193548  41.000000  19.870968
201506    5584.0  4885.0    ...     56.500000  41.400000  15.966667
201507    4214.0  3850.0    ...     38.967742  28.709677  14.548387
201508    4521.0  4093.0    ...     34.903226  28.483871  15.516129
201509    6146.0  5114.0    ...     46.333333  36.666667  17.466667
201510    6868.0  5357.0    ...     49.967742  39.677419  18.935484
201511    7404.0  5994.0    ...     51.600000  41.600000  18.500000
201512    9553.0  7560.0    ...     61.419355  50.129032  21.548387
201601    7834.0  6352.0    ...     58.419355  42.129032  17.258065
201602    9043.0  6920.0    ...     67.068966  40.689655  19.689655
201603    8585.0  7193.0    ...     65.290323  42.612903  19.774194
201604    8243.0  7369.0    ...     60.066667  39.100000  19.333333
201605    7078.0  6562.0    ...     56.709677  38.290323  19.129032
201606    5264.0  4938.0    ...     49.400000  31.533333  14.700000
201607    4576.0  4006.0    ...     38.161290  28.064516  14.677419
201608    4456.0  4310.0    ...     35.870968  27.677419  14.838710
201609    5532.0  5338.0    ...     40.000000  32.433333  16.300000
201610    6556.0  6019.0    ...     48.677419  34.225806  17.419355
201611    7585.0  6949.0    ...     48.900000  37.466667  19.833333
201612   10673.0  9120.0    ...     53.774194  39.967742  20.290323
201701    7417.0  6574.0    ...     47.903226  39.322581  16.064516
201702    6135.0  5433.0    ...     36.000000  39.392857  17.750000
201703    7363.0  6984.0    ...     37.838710  35.806452  18.870968
201704    7037.0  7344.0    ...     44.000000  41.066667  20.500000
201705    6285.0  6371.0    ...     34.451613  37.806452  19.548387
201706    4943.0  5299.0    ...     31.133333  32.900000  16.966667
201707    4125.0  4282.0    ...     26.580645  26.677419  15.290323
201708    4192.0  4416.0    ...     23.290323  25.258065  12.290323
201709    5389.0  5527.0    ...     26.866667  31.800000  18.366667
201710    5228.0  4720.0    ...     24.064516  27.161290  14.645161
201711    6633.0  6374.0    ...     29.733333  34.600000  17.500000
201712    8180.0  7194.0    ...     36.741935  42.258065  18.064516
201801    9056.0  7271.0    ...     43.838710  45.967742  24.258065
201802    5321.0  4698.0    ...     29.607143  38.000000  18.357143
201803    5344.0  5600.0    ...     28.064516  35.612903  19.290323
201804    6275.0  6328.0    ...     32.700000  37.200000  20.200000
201805    6240.0  5828.0    ...     30.806452  40.032258  20.645161
201806    4731.0  4898.0    ...     26.333333  30.733333  16.833333

                                                                         \

시군구지역코드      48870       48880      48890       49110       49130 49710
월별
201401   46.419355   74.516129  41.612903  298.516129  124.322581   NaN
201402   60.535714   93.750000  55.035714  328.571429  126.392857   1.0
201403   50.548387   73.032258  47.258065  306.387097  116.612903   1.0
201404   49.800000  104.933333  45.733333  348.400000  128.766667   1.0
201405   48.709677   70.612903  46.290323  313.709677  113.548387   1.0
201406   43.100000   51.866667  37.066667  256.066667  103.666667   1.0
201407   41.290323   43.838710  32.064516  227.419355   80.709677   1.0
201408   40.612903   36.290323  32.612903  222.032258   77.806452   1.0
201409   43.866667   59.733333  36.166667  298.633333   95.966667   1.0
201410   50.064516   64.483871  35.451613  329.290323  111.870968   1.0
201411   50.266667   73.600000  36.200000  371.233333  117.033333   1.0
201412   48.129032   50.322581  41.290323  389.032258  127.709677   1.0
201501   45.032258   56.387097  42.451613  319.451613  111.096774   NaN
201502   56.000000   64.500000  45.357143  299.714286  117.785714   NaN
201503   59.483871   79.354839  49.806452  344.419355  146.000000   NaN
201504   52.400000   66.300000  46.000000  364.200000  148.600000   NaN
201505   51.645161   74.709677  39.838710  293.387097  125.064516   NaN
201506   43.833333   60.266667  37.033333  233.266667  103.666667   NaN
201507   38.290323   39.483871  28.580645  168.516129   80.290323   NaN
201508   38.225806   44.677419  28.161290  174.548387   79.709677   NaN
201509   43.733333   63.333333  38.266667  264.500000   97.866667   NaN
201510   46.741935   72.870968  45.419355  281.354839  114.677419   NaN
201511   46.900000   93.500000  44.200000  301.166667  112.266667   NaN
201512   47.741935   67.387097  49.129032  360.032258  130.967742   NaN
201601   41.258065   53.354839  50.258065  293.935484  121.870968   NaN
201602   45.172414   57.275862  58.413793  316.310345  136.275862   NaN
201603   47.580645   66.064516  49.290323  342.032258  151.645161   NaN
201604   41.500000   60.566667  45.300000  331.633333  132.200000   NaN
201605   43.903226   50.258065  42.387097  307.645161  129.322581   NaN
201606   38.366667   36.733333  35.766667  265.900000  118.833333   NaN
201607   34.870968   50.935484  29.580645  193.419355   92.645161   NaN
201608   37.451613   53.290323  29.580645  189.709677   93.870968   NaN
201609   41.466667   81.433333  34.300000  227.766667  103.666667   NaN
201610   49.161290   83.935484  38.322581  267.741935  115.354839   NaN
201611   46.966667   98.400000  43.200000  319.533333  140.466667   NaN
201612   41.580645   59.000000  46.580645  371.096774  154.387097   NaN
201701   43.677419   52.580645  42.193548  287.612903  137.258065   NaN
201702   43.857143   55.642857  41.250000  261.678571  122.928571   NaN
201703   44.000000   57.258065  46.580645  279.709677  134.258065   NaN
201704   43.600000   51.766667  48.033333  289.900000  122.500000   NaN
201705   45.483871   44.774194  46.032258  286.548387  119.741935   NaN
201706   36.866667   35.600000  33.100000  231.300000  110.100000   NaN
201707   31.774194   36.387097  24.903226  163.645161   86.000000   NaN
201708   31.516129   32.838710  24.483871  166.225806   91.193548   NaN
201709   37.133333   35.533333  27.600000  233.533333  109.066667   NaN
201710   36.258065   45.000000  30.967742  213.580645  106.193548   NaN
201711   45.466667   62.166667  36.666667  309.566667  133.333333   NaN
201712   44.709677   44.483871  45.838710  346.354839  153.967742   NaN
201801   58.967742   60.258065  58.161290  349.000000  185.741935   NaN
201802   53.678571   49.000000  44.392857  258.142857  133.392857   NaN
201803   47.483871   51.677419  38.967742  279.032258  142.096774   NaN
201804   48.833333   50.133333  40.066667  306.166667  150.800000   NaN
201805   50.225806   43.645161  35.838710  293.612903  136.838710   NaN
201806   44.900000   34.633333  29.566667  231.566667  112.833333   NaN



시군구지역코드     49720
월별
201401   1.000000
201402   1.200000
201403   1.000000
201404   1.375000
201405   1.000000
201406   1.000000
201407   1.333333
201408   1.000000
201409   1.300000
201410   1.200000
201411   1.333333
201412   1.000000
201501        NaN
201502        NaN
201503        NaN
201504        NaN
201505        NaN
201506        NaN
201507        NaN
201508        NaN
201509        NaN
201510        NaN
201511        NaN
201512        NaN
201601        NaN
201602        NaN
201603        NaN
201604        NaN
201605        NaN
201606        NaN
201607        NaN
201608        NaN
201609        NaN
201610        NaN
201611        NaN
201612        NaN
201701        NaN
201702        NaN
201703        NaN
201704        NaN
201705        NaN
201706        NaN
201707        NaN
201708        NaN
201709        NaN
201710        NaN
201711        NaN
201712        NaN
201801        NaN
201802        NaN
201803        NaN
201804        NaN
201805        NaN
201806        NaN

[54 rows x 512 columns]

In [ ]:
# 눈병
eye_sigun=pd.read_csv('./data/realdiz/eye_sigun.csv', encoding = 'euc-kr')
eye_sigun.rename(columns={'발생건수(건)':'눈병 발생건수'}, inplace = True)
tmp_m = []
for n in range(len(eye_sigun)):
    tmp_m.append(eye_sigun['날짜'][n]//100)
eye_sigun['월별']=tmp_m
eye_m=eye_sigun.drop('날짜',1)
eye_d=eye_sigun.drop('월별',1)
eye_m_piv=eye_m.pivot_table(index='월별', columns='시군구지역코드', aggfunc = [np.sum, np.mean])
eye_m_piv

In [279]:
# 피부염
skin_sigun=pd.read_csv('./data/realdiz/skin_sigun.csv', encoding = 'euc-kr')
skin_sigun.rename(columns={'발생건수(건)':'피부염 발생건수'}, inplace = True)
tmp_m = []
for n in range(len(skin_sigun)):
    tmp_m.append(skin_sigun['날짜'][n]//100)
skin_sigun['월별']=tmp_m
skin_m=skin_sigun.drop('날짜',1)
skin_d=skin_sigun.drop('월별',1)
skin_m_piv=skin_m.pivot_table(index='월별', columns='시군구지역코드', aggfunc = [np.sum, np.mean])
skin_m_piv

             sum                                                               \
        피부염 발생건수
시군구지역코드    11110   11140   11170    11200    11215    11230    11260    11290
월별
201401    3136.0  3388.0  5116.0   8942.0   9267.0   9457.0  10320.0  10450.0
201402    3018.0  3363.0  5055.0   8417.0   8957.0   9349.0  10260.0  10307.0
201403    3264.0  3585.0  5579.0   9665.0  10030.0  10237.0  11192.0  11328.0
201404    3703.0  4054.0  6381.0  10988.0  11361.0  11771.0  12714.0  12731.0
201405    4082.0  4582.0  7121.0  12184.0  12650.0  13258.0  14418.0  14349.0
201406    3941.0  4234.0  6614.0  11803.0  11965.0  12446.0  13402.0  13585.0
201407    4457.0  4822.0  7207.0  12797.0  13177.0  13722.0  14247.0  14965.0
201408    4013.0  4280.0  6414.0  11665.0  11865.0  12352.0  13445.0  13782.0
201409    3809.0  4086.0  6372.0  11257.0  11733.0  11775.0  12782.0  13343.0
201410    3583.0  3907.0  5925.0  10098.0  10628.0  10868.0  11876.0  12313.0
201411    3068.0  3468.0  4980.0   8854.0   8956.0   9497.0  10462.0  10478.0
201412    3168.0  3577.0  5320.0   8987.0   9393.0   9798.0  11064.0  10719.0
201501    3233.0  3501.0  5251.0   8933.0   9578.0   9644.0  10615.0  10460.0
201502    2770.0  3213.0  4803.0   7910.0   8692.0   8832.0   9489.0   9628.0
201503    3726.0  3871.0  5773.0   9896.0  10673.0  11212.0  11861.0  11953.0
201504    3647.0  3717.0  5964.0   9950.0  10862.0  11252.0  12224.0  11667.0
201505    3909.0  4344.0  6759.0  11503.0  12230.0  12939.0  13758.0  13879.0
201506    3712.0  3993.0  6074.0  10391.0  10829.0  11644.0  12367.0  12360.0
201507    3914.0  4475.0  6833.0  11631.0  11788.0  12574.0  13524.0  13567.0
201508    4068.0  4361.0  6745.0  11944.0  11856.0  12301.0  13473.0  13498.0
201509    3592.0  3886.0  5977.0  10332.0  10871.0  11104.0  12413.0  12349.0
201510    3436.0  3718.0  5721.0   9846.0  10408.0  10853.0  11832.0  11867.0
201511    3157.0  3126.0  4897.0   8356.0   8850.0   9327.0  10277.0   9693.0
201512    3202.0  3228.0  5284.0   9085.0   9695.0  10104.0  10812.0  10581.0
201601    3103.0  3142.0  5079.0   8784.0   9094.0   9713.0  10169.0  10312.0
201602    3040.0  3262.0  4900.0   8700.0   9001.0   9658.0  10303.0  10259.0
201603    3710.0  3508.0  5544.0   9737.0  10117.0  11190.0  11642.0  11678.0
201604    3758.0  3508.0  5754.0  10076.0  10977.0  11637.0  12468.0  12304.0
201605    4350.0  4080.0  6542.0  11369.0  12209.0  12873.0  13488.0  13604.0
201606    4353.0  4303.0  6334.0  11549.0  11694.0  12547.0  12929.0  13329.0
201607    4486.0  4246.0  6525.0  11430.0  11788.0  13028.0  13284.0  13599.0
201608    4720.0  4404.0  6920.0  12265.0  12367.0  14280.0  13949.0  14243.0
201609    3911.0  3738.0  5818.0  10130.0  10666.0  11766.0  11764.0  12415.0
201610    3731.0  3445.0  5522.0   9691.0  10019.0  10895.0  11101.0  11881.0
201611    3683.0  3401.0  5254.0   9358.0   9716.0  10073.0  10550.0  10635.0
201612    3434.0  3078.0  4959.0   9078.0   9235.0   9957.0  10086.0  10328.0
201701    3240.0  2996.0  4815.0   8589.0   8532.0   9400.0   9509.0   9793.0
201702    3213.0  3247.0  4850.0   8802.0   8731.0   9640.0   9740.0   9924.0
201703    3680.0  3405.0  5620.0  10325.0   9732.0  10737.0  10872.0  10961.0
201704    3677.0  3329.0  5615.0  10008.0  10067.0  10518.0  11291.0  11214.0
201705    4443.0  4134.0  6329.0  11576.0  11959.0  12771.0  13418.0  13652.0
201706    4564.0  4013.0  6280.0  11247.0  11530.0  12368.0  12725.0  12875.0
201707    4783.0  4172.0  6698.0  11753.0  12019.0  12782.0  13224.0  13770.0
201708    4782.0  4227.0  6762.0  12303.0  11885.0  12652.0  13338.0  14024.0
201709    4354.0  3958.0  6254.0  11405.0  11667.0  12024.0  12505.0  13207.0
201710    3482.0  3104.0  4952.0   9051.0   9301.0   9557.0  10054.0  10255.0
201711    3614.0  3338.0  5208.0   9749.0   9611.0   9835.0  10289.0  10964.0
201712    3288.0  2997.0  4799.0   9042.0   9030.0   9009.0   8996.0   9918.0
201801    3458.0  3192.0  5071.0   9108.0   9390.0   9163.0   9633.0  10192.0
201802    3154.0  2859.0  4505.0   8567.0   8669.0   8454.0   8824.0   9306.0
201803    3637.0  3326.0  5459.0   9906.0  10025.0   9854.0  10460.0  10701.0
201804    3880.0  3606.0  5772.0  10517.0  10885.0  10476.0  10968.0  10954.0
201805    4142.0  4054.0  6230.0  11016.0  11971.0  11505.0  12974.0  12338.0
201806    4125.0  4082.0  6268.0  11810.0  12090.0  11635.0  13092.0  12662.0

                            ...           mean                        \
                            ...       피부염 발생건수
시군구지역코드    11305   11320    ...          48840      48850      48860
월별                          ...
201401    8109.0  6677.0    ...      35.322581  55.677419  30.129032
201402    7865.0  6568.0    ...      37.071429  59.142857  30.892857
201403    8992.0  7362.0    ...      45.000000  64.258065  33.258065
201404   10024.0  8009.0    ...      56.633333  69.833333  40.033333
201405   11395.0  8979.0    ...      70.612903  78.322581  41.225806
201406   11218.0  8839.0    ...      83.833333  91.433333  44.600000
201407   11992.0  9622.0    ...     103.612903  87.387097  51.483871
201408   11192.0  9216.0    ...      89.806452  88.838710  49.903226
201409   10519.0  8932.0    ...      93.433333  86.500000  54.866667
201410    9625.0  7857.0    ...      60.483871  75.806452  51.483871
201411    8148.0  6507.0    ...      51.200000  59.266667  37.266667
201412    8484.0  6915.0    ...      53.419355  51.161290  35.451613
201501    8443.0  6752.0    ...      55.516129  55.064516  36.483871
201502    7468.0  6209.0    ...      54.142857  50.500000  36.071429
201503    9383.0  7689.0    ...      62.548387  52.387097  43.129032
201504    9510.0  7672.0    ...      67.266667  60.900000  42.066667
201505   10994.0  8835.0    ...      74.677419  72.161290  47.677419
201506   10268.0  8148.0    ...      92.133333  90.200000  47.133333
201507   10521.0  8925.0    ...     108.161290  94.806452  52.161290
201508   10789.0  8469.0    ...     111.967742  93.096774  48.903226
201509    9709.0  7517.0    ...      96.900000  81.200000  44.966667
201510    9066.0  7150.0    ...      74.064516  72.096774  44.903226
201511    7824.0  6277.0    ...      65.466667  52.466667  34.666667
201512    8402.0  6432.0    ...      63.741935  54.645161  35.032258
201601    8143.0  6284.0    ...      59.258065  51.645161  33.387097
201602    8134.0  6349.0    ...      59.310345  53.068966  32.724138
201603    9319.0  7175.0    ...      70.290323  57.096774  37.677419
201604    9560.0  7478.0    ...      75.100000  63.800000  42.233333
201605   10559.0  8531.0    ...      82.096774  73.870968  45.322581
201606   10322.0  8215.0    ...     102.666667  85.233333  47.200000
201607   10351.0  8587.0    ...     124.741935  90.258065  56.709677
201608   11467.0  9540.0    ...     128.064516  87.354839  53.451613
201609    9313.0  7886.0    ...      96.133333  76.833333  48.266667
201610    8742.0  7158.0    ...      73.580645  74.612903  49.870968
201611    8013.0  6678.0    ...      60.733333  66.900000  39.700000
201612    8153.0  6465.0    ...      50.419355  52.032258  36.129032
201701    7680.0  6057.0    ...      53.612903  44.709677  40.838710
201702    7513.0  6139.0    ...      63.964286  60.392857  42.178571
201703    8891.0  7031.0    ...      74.129032  53.806452  43.483871
201704    8757.0  7062.0    ...      68.266667  60.333333  46.266667
201705   10419.0  8447.0    ...      79.838710  68.225806  45.645161
201706    9921.0  8170.0    ...      87.800000  80.633333  48.433333
201707   10635.0  8760.0    ...     115.000000  95.903226  56.258065
201708   10906.0  8915.0    ...     100.677419  91.806452  49.612903
201709   10307.0  8624.0    ...      91.833333  89.166667  47.166667
201710    7931.0  6761.0    ...      62.967742  67.709677  43.967742
201711    8242.0  6762.0    ...      52.033333  75.400000  39.466667
201712    7758.0  6126.0    ...      44.903226  51.322581  31.193548
201801    7867.0  6490.0    ...      47.612903  52.677419  35.129032
201802    7290.0  5942.0    ...      48.892857  55.642857  37.285714
201803    8584.0  7016.0    ...      53.870968  54.741935  40.096774
201804    8894.0  7546.0    ...      65.233333  65.666667  46.933333
201805    9690.0  7917.0    ...      68.161290  79.483871  49.193548
201806    9758.0  8163.0    ...      81.500000  91.933333  46.700000

                                                                            \

시군구지역코드      48870      48880      48890       49110       49130     49710
월별
201401   36.258065  48.741935  45.580645  290.354839  115.806452  1.166667
201402   39.642857  47.857143  46.642857  299.607143  126.000000  1.333333
201403   40.903226  50.612903  53.419355  319.419355  128.000000  1.000000
201404   47.666667  62.266667  59.933333  377.600000  142.566667  1.000000
201405   49.322581  69.096774  62.322581  434.548387  166.225806  1.000000
201406   49.033333  69.966667  66.233333  446.000000  181.033333  1.000000
201407   58.225806  75.935484  74.193548  507.129032  198.193548  1.555556
201408   52.290323  66.580645  72.129032  459.967742  175.741935  1.375000
201409   53.700000  73.033333  68.666667  471.566667  191.100000  1.285714
201410   44.580645  65.193548  60.516129  383.580645  139.451613  1.000000
201411   35.100000  50.900000  48.733333  328.166667  122.300000  1.000000
201412   32.129032  51.258065  49.838710  311.612903  112.096774  1.000000
201501   37.709677  55.064516  57.161290  324.322581  108.516129       NaN
201502   38.821429  51.821429  55.428571  333.535714  111.250000       NaN
201503   41.806452  56.322581  58.516129  357.677419  122.935484       NaN
201504   42.766667  60.633333  62.500000  378.733333  129.400000       NaN
201505   49.193548  74.290323  63.161290  451.322581  156.580645       NaN
201506   46.266667  67.133333  63.100000  521.166667  165.833333       NaN
201507   53.129032  76.935484  71.225806  535.129032  183.548387       NaN
201508   51.967742  73.580645  69.516129  485.129032  173.903226       NaN
201509   47.666667  59.033333  70.533333  489.600000  158.233333       NaN
201510   45.709677  66.483871  64.161290  412.709677  147.870968       NaN
201511   38.033333  47.333333  50.600000  335.566667  130.033333       NaN
201512   36.290323  48.580645  47.967742  330.161290  131.354839       NaN
201601   38.516129  46.419355  47.096774  306.612903  132.064516       NaN
201602   40.620690  45.379310  47.068966  354.965517  135.586207       NaN
201603   40.193548  50.612903  52.032258  356.903226  138.129032       NaN
201604   47.933333  62.833333  57.733333  380.833333  134.466667       NaN
201605   50.129032  72.806452  58.193548  443.935484  154.741935       NaN
201606   51.266667  78.066667  64.000000  556.400000  179.366667       NaN
201607   56.354839  80.064516  69.419355  547.548387  196.225806       NaN
201608   58.645161  80.419355  71.322581  533.903226  206.322581       NaN
201609   55.233333  72.033333  65.733333  531.066667  170.300000       NaN
201610   50.580645  73.225806  61.580645  406.483871  154.483871       NaN
201611   40.166667  60.733333  54.133333  370.666667  153.133333       NaN
201612   41.806452  54.838710  50.354839  342.806452  140.774194       NaN
201701   37.483871  48.612903  47.967742  311.258065  129.419355       NaN
201702   43.321429  56.750000  55.464286  348.678571  141.964286       NaN
201703   39.806452  59.967742  57.516129  355.516129  157.322581       NaN
201704   45.233333  66.400000  58.100000  379.300000  144.200000       NaN
201705   53.580645  75.548387  61.483871  467.483871  176.548387       NaN
201706   53.733333  68.700000  64.200000  555.433333  185.800000       NaN
201707   62.032258  76.935484  74.000000  561.161290  202.838710       NaN
201708   60.354839  78.322581  72.870968  486.032258  206.419355       NaN
201709   54.866667  81.233333  67.433333  456.966667  186.300000       NaN
201710   46.161290  61.354839  50.870968  350.129032  147.677419       NaN
201711   37.166667  60.066667  47.366667  379.700000  168.333333       NaN
201712   36.483871  53.032258  42.290323  326.709677  142.225806       NaN
201801   36.774194  51.064516  41.225806  333.967742  136.129032       NaN
201802   37.250000  54.321429  43.214286  348.750000  137.178571       NaN
201803   44.000000  58.161290  50.580645  380.193548  145.612903       NaN
201804   48.866667  70.333333  57.400000  432.033333  160.466667       NaN
201805   48.967742  89.258065  61.064516  455.548387  167.290323       NaN
201806   51.100000  87.000000  61.500000  511.100000  188.133333       NaN



시군구지역코드     49720
월별
201401   1.200000
201402   1.111111
201403   1.000000
201404   1.333333
201405   1.125000
201406   1.000000
201407   1.222222
201408   1.142857
201409   1.000000
201410   1.000000
201411   1.000000
201412   1.000000
201501        NaN
201502        NaN
201503        NaN
201504        NaN
201505        NaN
201506        NaN
201507        NaN
201508        NaN
201509        NaN
201510        NaN
201511        NaN
201512        NaN
201601        NaN
201602        NaN
201603        NaN
201604        NaN
201605        NaN
201606        NaN
201607        NaN
201608        NaN
201609        NaN
201610        NaN
201611        NaN
201612        NaN
201701        NaN
201702        NaN
201703        NaN
201704        NaN
201705        NaN
201706        NaN
201707        NaN
201708        NaN
201709        NaN
201710        NaN
201711        NaN
201712        NaN
201801        NaN
201802        NaN
201803        NaN
201804        NaN
201805        NaN
201806        NaN

[54 rows x 514 columns]

In [482]:
tmp_name = location(cold_m_piv)

In [485]:
cold_m_piv.rename= tmp_name

In [488]:
cold_m

        시군구지역코드  감기 발생건수      월별
0         11110       53  201401
1         11140       55  201401
2         11170      120  201401
3         11200      192  201401
4         11215      165  201401
5         11230      156  201401
6         11260      211  201401
7         11290      174  201401
8         11305      185  201401
9         11320      204  201401
10        11350      512  201401
11        11380      319  201401
12        11410      187  201401
13        11440      241  201401
14        11470      340  201401
15        11500      552  201401
16        11530      360  201401
17        11545      150  201401
18        11560      190  201401
19        11590      224  201401
20        11620      289  201401
21        11650      295  201401
22        11680      205  201401
23        11710      316  201401
24        11740      297  201401
25        26110       31  201401
26        26140      114  201401
27        26170       80  201401
28        26200       90  201401
29        26230      396  201401
...         ...      ...     ...
413262    47840      156  201806
413263    47850      594  201806
413264    47900      190  201806
413265    47920       89  201806
413266    47930      165  201806
413267    47940       18  201806
413268    48121     1081  201806
413269    48123      888  201806
413270    48125      663  201806
413271    48127      728  201806
413272    48129      870  201806
413273    48170     1291  201806
413274    48220      591  201806
413275    48240      583  201806
413276    48250     2661  201806
413277    48270      421  201806
413278    48310     1343  201806
413279    48330     1929  201806
413280    48720       81  201806
413281    48730      256  201806
413282    48740      239  201806
413283    48820      176  201806
413284    48840      152  201806
413285    48850      129  201806
413286    48860       94  201806
413287    48870      140  201806
413288    48880      188  201806
413289    48890      123  201806
413290    49110     1896  201806
413291    49130      726  201806

[413292 rows x 3 columns]

In [453]:
local_code

     시군구지역코드           지역명
0      11110        서울 종로구
1      11140         서울 중구
2      11170        서울 용산구
3      11200        서울 성동구
4      11215        서울 광진구
5      11230       서울 동대문구
6      11260        서울 중랑구
7      11290        서울 성북구
8      11305        서울 강북구
9      11320        서울 도봉구
10     11350        서울 노원구
11     11380        서울 은평구
12     11410       서울 서대문구
13     11440        서울 마포구
14     11470        서울 양천구
15     11500        서울 강서구
16     11530        서울 구로구
17     11545        서울 금천구
18     11560       서울 영등포구
19     11590        서울 동작구
20     11620        서울 관악구
21     11650        서울 서초구
22     11680        서울 강남구
23     11710        서울 송파구
24     11740        서울 강동구
25     26110         부산 중구
26     26140         부산 서구
27     26170         부산 동구
28     26200        부산 영도구
29     26230       부산 부산진구
..       ...           ...
223    47840        경북 성주군
224    47850        경북 칠곡군
225    47900        경북 예천군
226    47920        경북 봉화군
227    47930        경북 울진군
228    47940        경북 울릉군
229    48121    경남 창원시 의창구
230    48123    경남 창원시 성산구
231    48125  경남 창원시 마산합포구
232    48127  경남 창원시 마산회원구
233    48129    경남 창원시 진해구
234    48170        경남 진주시
235    48220        경남 통영시
236    48240        경남 사천시
237    48250        경남 김해시
238    48270        경남 밀양시
239    48310        경남 거제시
240    48330        경남 양산시
241    48720        경남 의령군
242    48730        경남 함안군
243    48740        경남 창녕군
244    48820        경남 고성군
245    48840        경남 남해군
246    48850        경남 하동군
247    48860        경남 산청군
248    48870        경남 함양군
249    48880        경남 거창군
250    48890        경남 합천군
251    49110        제주 제주시
252    49130       제주 서귀포시

[253 rows x 2 columns]

In [285]:
# #이름 맞추기
# #이름 깊이까지 내려가기
# skin_m_piv.columns.levels[2]

Int64Index([11110, 11140, 11170, 11200, 11215, 11230, 11260, 11290, 11305,
            11320,
            ...
            48840, 48850, 48860, 48870, 48880, 48890, 49110, 49130, 49710,
            49720],
           dtype='int64', name='시군구지역코드', length=257)

In [286]:
cold_m.to_csv('./data/cold_m.csv',sep=',',encoding='utf-8-sig')
breath_m.to_csv('./data/breath_m.csv',sep=',',encoding='utf-8-sig')
eye_m.to_csv('./data/eye_m.csv',sep=',',encoding='utf-8-sig')
skin_m.to_csv('./data/skin_m.csv',sep=',',encoding='utf-8-sig')

In [312]:
#breath_m.pivot_table(index='월별', columns='시군구지역코드',aggfunc=np.sum)

        천식 발생건수                                                             \
시군구지역코드   11110   11140   11170   11200    11215   11230    11260    11290
월별
201401   2113.0  2657.0  3342.0  4636.0   8174.0  5677.0   8691.0   9742.0
201402   2194.0  3153.0  3434.0  4840.0   8955.0  6620.0   9852.0  10998.0
201403   2012.0  3015.0  3580.0  4663.0   9076.0  6354.0   9550.0   9618.0
201404   2229.0  3830.0  3865.0  5467.0   9490.0  7327.0  10042.0  10795.0
201405   2146.0  3005.0  3461.0  4714.0   7921.0  5957.0   8772.0   9878.0
201406   1531.0  2354.0  2617.0  3642.0   6151.0  4484.0   6271.0   6969.0
201407   1482.0  2089.0  2488.0  3947.0   5759.0  4411.0   5648.0   6804.0
201408   1395.0  1895.0  2383.0  3355.0   5137.0  3957.0   5308.0   6133.0
201409   1740.0  2546.0  3117.0  4521.0   7050.0  5428.0   7101.0   7854.0
201410   1958.0  2830.0  3558.0  5199.0   8446.0  6325.0   8267.0   9130.0
201411   2131.0  3189.0  3848.0  5637.0   9194.0  7249.0   8956.0   9514.0
201412   2219.0  3083.0  4050.0  5766.0   8955.0  6915.0   8906.0  10565.0
201501   2031.0  2672.0  3249.0  4970.0   7668.0  5951.0   8059.0   8083.0
201502   1951.0  2291.0  3202.0  4740.0   7802.0  5700.0   7382.0   7614.0
201503   2190.0  2614.0  3445.0  5435.0   8087.0  6586.0   8331.0   8565.0
201504   2243.0  2587.0  3752.0  5597.0   8699.0  6755.0   7980.0   8911.0
201505   1858.0  2023.0  3170.0  4561.0   7560.0  6052.0   7611.0   7872.0
201506   1296.0  1555.0  2338.0  3360.0   4747.0  4082.0   5791.0   5284.0
201507   1127.0  1282.0  1969.0  3182.0   4102.0  3509.0   5129.0   4499.0
201508   1318.0  1347.0  2315.0  3685.0   4701.0  3886.0   5645.0   5044.0
201509   1684.0  1978.0  3006.0  4678.0   6849.0  5047.0   7263.0   6539.0
201510   1678.0  2198.0  3314.0  5210.0   7909.0  5352.0   7687.0   7155.0
201511   1726.0  2323.0  3278.0  6026.0   7970.0  5668.0   8382.0   7044.0
201512   1861.0  2983.0  4235.0  6469.0   9659.0  7182.0  10191.0   9265.0
201601   1652.0  2133.0  3432.0  5118.0   7713.0  5782.0   8602.0   7198.0
201602   1786.0  2163.0  3141.0  5577.0   8453.0  6454.0   8651.0   7282.0
201603   1861.0  2401.0  3695.0  6081.0   8552.0  6448.0   9024.0   7290.0
201604   1925.0  2380.0  3475.0  6035.0   8820.0  6257.0   9096.0   7263.0
201605   1818.0  2306.0  3317.0  4891.0   8061.0  5550.0   8280.0   6533.0
201606   1259.0  1611.0  2510.0  3922.0   5561.0  4296.0   6305.0   5155.0
201607   1149.0  1300.0  2266.0  3266.0   5112.0  3764.0   5438.0   4518.0
201608   1189.0  1301.0  2194.0  3266.0   4580.0  3609.0   5228.0   4277.0
201609   1475.0  1746.0  2827.0  4368.0   6207.0  4514.0   6530.0   5179.0
201610   1552.0  2113.0  3239.0  5380.0   7309.0  5493.0   7544.0   6211.0
201611   1913.0  2545.0  3681.0  6263.0   8668.0  6358.0   8748.0   7054.0
201612   2467.0  2916.0  4328.0  7902.0  11708.0  8451.0  10347.0   8883.0
201701   1780.0  2267.0  2980.0  4969.0   7562.0  5418.0   7315.0   5984.0
201702   1335.0  1860.0  2844.0  4305.0   6910.0  4804.0   6587.0   5290.0
201703   1755.0  2252.0  3478.0  5671.0   8435.0  6070.0   7945.0   6271.0
201704   1743.0  2120.0  3594.0  5911.0   8834.0  6293.0   8143.0   6639.0
201705   1612.0  1919.0  3205.0  5024.0   7324.0  5220.0   7546.0   5895.0
201706   1278.0  1658.0  2630.0  3886.0   5808.0  4275.0   5641.0   4784.0
201707   1118.0  1241.0  2275.0  3550.0   4707.0  3715.0   5093.0   4122.0
201708   1265.0  1253.0  2143.0  3264.0   4415.0  3387.0   4853.0   3985.0
201709   1521.0  1605.0  2911.0  4373.0   6496.0  4569.0   6071.0   5239.0
201710   1311.0  1557.0  2501.0  3872.0   6051.0  4430.0   5846.0   4606.0
201711   1622.0  2108.0  3355.0  5440.0   8266.0  6291.0   8053.0   6338.0
201712   1855.0  2367.0  3462.0  5612.0   9460.0  7019.0   8987.0   7302.0
201801   2055.0  2463.0  3312.0  5187.0   8122.0  6415.0   8031.0   6971.0
201802   1399.0  1721.0  2264.0  3642.0   5261.0  4781.0   5711.0   5039.0
201803   1456.0  2065.0  2754.0  4149.0   5821.0  5322.0   6832.0   5380.0
201804   1698.0  2471.0  3109.0  4975.0   6518.0  5733.0   7386.0   6284.0
201805   1612.0  2041.0  2995.0  4947.0   5885.0  5525.0   6581.0   5849.0
201806   1240.0  1546.0  2300.0  3711.0   4403.0  4355.0   5262.0   4620.0

                          ...                                                  \
시군구지역코드    11305   11320  ...    48840   48850  48860   48870   48880   48890
월별                        ...
201401    9074.0  7843.0  ...   2023.0  1327.0  554.0  1439.0  2310.0  1290.0
201402   11253.0  8519.0  ...   2027.0  1425.0  560.0  1695.0  2625.0  1541.0
201403    9344.0  7842.0  ...   2049.0  1293.0  486.0  1567.0  2264.0  1465.0
201404    9989.0  8520.0  ...   1973.0  1208.0  600.0  1494.0  3148.0  1372.0
201405    8671.0  7594.0  ...   1792.0  1164.0  566.0  1510.0  2189.0  1435.0
201406    6345.0  5652.0  ...   1267.0   948.0  445.0  1293.0  1556.0  1112.0
201407    6329.0  5823.0  ...   1280.0   901.0  433.0  1280.0  1359.0   994.0
201408    5679.0  5125.0  ...   1278.0   855.0  448.0  1259.0  1125.0  1011.0
201409    7061.0  6384.0  ...   1528.0  1053.0  469.0  1316.0  1792.0  1085.0
201410    8131.0  7249.0  ...   1557.0  1002.0  482.0  1552.0  1999.0  1099.0
201411    8099.0  7753.0  ...   1825.0  1014.0  512.0  1508.0  2208.0  1086.0
201412    8964.0  7997.0  ...   1908.0  1216.0  549.0  1492.0  1560.0  1280.0
201501    8077.0  7043.0  ...   2022.0  1173.0  513.0  1396.0  1748.0  1316.0
201502    8294.0  6604.0  ...   1997.0  1269.0  550.0  1568.0  1806.0  1270.0
201503    8943.0  7177.0  ...   1997.0  1403.0  652.0  1844.0  2460.0  1544.0
201504    8436.0  7437.0  ...   2084.0  1311.0  623.0  1572.0  1989.0  1380.0
201505    7190.0  6226.0  ...   1897.0  1271.0  616.0  1601.0  2316.0  1235.0
201506    5584.0  4885.0  ...   1695.0  1242.0  479.0  1315.0  1808.0  1111.0
201507    4214.0  3850.0  ...   1208.0   890.0  451.0  1187.0  1224.0   886.0
201508    4521.0  4093.0  ...   1082.0   883.0  481.0  1185.0  1385.0   873.0
201509    6146.0  5114.0  ...   1390.0  1100.0  524.0  1312.0  1900.0  1148.0
201510    6868.0  5357.0  ...   1549.0  1230.0  587.0  1449.0  2259.0  1408.0
201511    7404.0  5994.0  ...   1548.0  1248.0  555.0  1407.0  2805.0  1326.0
201512    9553.0  7560.0  ...   1904.0  1554.0  668.0  1480.0  2089.0  1523.0
201601    7834.0  6352.0  ...   1811.0  1306.0  535.0  1279.0  1654.0  1558.0
201602    9043.0  6920.0  ...   1945.0  1180.0  571.0  1310.0  1661.0  1694.0
201603    8585.0  7193.0  ...   2024.0  1321.0  613.0  1475.0  2048.0  1528.0
201604    8243.0  7369.0  ...   1802.0  1173.0  580.0  1245.0  1817.0  1359.0
201605    7078.0  6562.0  ...   1758.0  1187.0  593.0  1361.0  1558.0  1314.0
201606    5264.0  4938.0  ...   1482.0   946.0  441.0  1151.0  1102.0  1073.0
201607    4576.0  4006.0  ...   1183.0   870.0  455.0  1081.0  1579.0   917.0
201608    4456.0  4310.0  ...   1112.0   858.0  460.0  1161.0  1652.0   917.0
201609    5532.0  5338.0  ...   1200.0   973.0  489.0  1244.0  2443.0  1029.0
201610    6556.0  6019.0  ...   1509.0  1061.0  540.0  1524.0  2602.0  1188.0
201611    7585.0  6949.0  ...   1467.0  1124.0  595.0  1409.0  2952.0  1296.0
201612   10673.0  9120.0  ...   1667.0  1239.0  629.0  1289.0  1829.0  1444.0
201701    7417.0  6574.0  ...   1485.0  1219.0  498.0  1354.0  1630.0  1308.0
201702    6135.0  5433.0  ...   1008.0  1103.0  497.0  1228.0  1558.0  1155.0
201703    7363.0  6984.0  ...   1173.0  1110.0  585.0  1364.0  1775.0  1444.0
201704    7037.0  7344.0  ...   1320.0  1232.0  615.0  1308.0  1553.0  1441.0
201705    6285.0  6371.0  ...   1068.0  1172.0  606.0  1410.0  1388.0  1427.0
201706    4943.0  5299.0  ...    934.0   987.0  509.0  1106.0  1068.0   993.0
201707    4125.0  4282.0  ...    824.0   827.0  474.0   985.0  1128.0   772.0
201708    4192.0  4416.0  ...    722.0   783.0  381.0   977.0  1018.0   759.0
201709    5389.0  5527.0  ...    806.0   954.0  551.0  1114.0  1066.0   828.0
201710    5228.0  4720.0  ...    746.0   842.0  454.0  1124.0  1395.0   960.0
201711    6633.0  6374.0  ...    892.0  1038.0  525.0  1364.0  1865.0  1100.0
201712    8180.0  7194.0  ...   1139.0  1310.0  560.0  1386.0  1379.0  1421.0
201801    9056.0  7271.0  ...   1359.0  1425.0  752.0  1828.0  1868.0  1803.0
201802    5321.0  4698.0  ...    829.0  1064.0  514.0  1503.0  1372.0  1243.0
201803    5344.0  5600.0  ...    870.0  1104.0  598.0  1472.0  1602.0  1208.0
201804    6275.0  6328.0  ...    981.0  1116.0  606.0  1465.0  1504.0  1202.0
201805    6240.0  5828.0  ...    955.0  1241.0  640.0  1557.0  1353.0  1111.0
201806    4731.0  4898.0  ...    790.0   922.0  505.0  1347.0  1039.0   887.0


시군구지역코드    49110   49130 49710 49720
월별
201401    9254.0  3854.0   NaN   4.0
201402    9200.0  3539.0   2.0  12.0
201403    9498.0  3615.0   2.0   4.0
201404   10452.0  3863.0   3.0  11.0
201405    9725.0  3520.0   2.0   3.0
201406    7682.0  3110.0   4.0   6.0
201407    7050.0  2502.0   3.0   4.0
201408    6883.0  2412.0   3.0   2.0
201409    8959.0  2879.0   6.0  13.0
201410   10208.0  3468.0   2.0   6.0
201411   11137.0  3511.0   3.0  12.0
201412   12060.0  3959.0  15.0   4.0
201501    9903.0  3444.0   NaN   NaN
201502    8392.0  3298.0   NaN   NaN
201503   10677.0  4526.0   NaN   NaN
201504   10926.0  4458.0   NaN   NaN
201505    9095.0  3877.0   NaN   NaN
201506    6998.0  3110.0   NaN   NaN
201507    5224.0  2489.0   NaN   NaN
201508    5411.0  2471.0   NaN   NaN
201509    7935.0  2936.0   NaN   NaN
201510    8722.0  3555.0   NaN   NaN
201511    9035.0  3368.0   NaN   NaN
201512   11161.0  4060.0   NaN   NaN
201601    9112.0  3778.0   NaN   NaN
201602    9173.0  3952.0   NaN   NaN
201603   10603.0  4701.0   NaN   NaN
201604    9949.0  3966.0   NaN   NaN
201605    9537.0  4009.0   NaN   NaN
201606    7977.0  3565.0   NaN   NaN
201607    5996.0  2872.0   NaN   NaN
201608    5881.0  2910.0   NaN   NaN
201609    6833.0  3110.0   NaN   NaN
201610    8300.0  3576.0   NaN   NaN
201611    9586.0  4214.0   NaN   NaN
201612   11504.0  4786.0   NaN   NaN
201701    8916.0  4255.0   NaN   NaN
201702    7327.0  3442.0   NaN   NaN
201703    8671.0  4162.0   NaN   NaN
201704    8697.0  3675.0   NaN   NaN
201705    8883.0  3712.0   NaN   NaN
201706    6939.0  3303.0   NaN   NaN
201707    5073.0  2666.0   NaN   NaN
201708    5153.0  2827.0   NaN   NaN
201709    7006.0  3272.0   NaN   NaN
201710    6621.0  3292.0   NaN   NaN
201711    9287.0  4000.0   NaN   NaN
201712   10737.0  4773.0   NaN   NaN
201801   10819.0  5758.0   NaN   NaN
201802    7228.0  3735.0   NaN   NaN
201803    8650.0  4405.0   NaN   NaN
201804    9185.0  4524.0   NaN   NaN
201805    9102.0  4242.0   NaN   NaN
201806    6947.0  3385.0   NaN   NaN

[54 rows x 256 columns]

In [315]:
cold_m

        시군구지역코드  감기 발생건수      월별
0         11110       53  201401
1         11140       55  201401
2         11170      120  201401
3         11200      192  201401
4         11215      165  201401
5         11230      156  201401
6         11260      211  201401
7         11290      174  201401
8         11305      185  201401
9         11320      204  201401
10        11350      512  201401
11        11380      319  201401
12        11410      187  201401
13        11440      241  201401
14        11470      340  201401
15        11500      552  201401
16        11530      360  201401
17        11545      150  201401
18        11560      190  201401
19        11590      224  201401
20        11620      289  201401
21        11650      295  201401
22        11680      205  201401
23        11710      316  201401
24        11740      297  201401
25        26110       31  201401
26        26140      114  201401
27        26170       80  201401
28        26200       90  201401
29        26230      396  201401
...         ...      ...     ...
413262    47840      156  201806
413263    47850      594  201806
413264    47900      190  201806
413265    47920       89  201806
413266    47930      165  201806
413267    47940       18  201806
413268    48121     1081  201806
413269    48123      888  201806
413270    48125      663  201806
413271    48127      728  201806
413272    48129      870  201806
413273    48170     1291  201806
413274    48220      591  201806
413275    48240      583  201806
413276    48250     2661  201806
413277    48270      421  201806
413278    48310     1343  201806
413279    48330     1929  201806
413280    48720       81  201806
413281    48730      256  201806
413282    48740      239  201806
413283    48820      176  201806
413284    48840      152  201806
413285    48850      129  201806
413286    48860       94  201806
413287    48870      140  201806
413288    48880      188  201806
413289    48890      123  201806
413290    49110     1896  201806
413291    49130      726  201806

[413292 rows x 3 columns]

# 4대 질병  시군구 지역코드 고치기

In [316]:
#지역
local_code=pd.read_csv('./data/local_code.csv',sep=',',encoding='utf-8-sig')

In [321]:
local_code['시군구지역코드'][1], cold_m['시군구지역코드'][1]

(11140, 11140)

In [325]:
cold_m.head()

   시군구지역코드  감기 발생건수      월별
0    11110       53  201401
1    11140       55  201401
2    11170      120  201401
3    11200      192  201401
4    11215      165  201401

In [327]:
len(cold_m),len(local_code)

(413292, 253)

In [345]:
cold_name = cold_m.pivot_table(index='월별', columns='시군구지역코드',aggfunc=np.sum)

In [356]:
cold_name.columns.levels[1]

Int64Index([11110, 11140, 11170, 11200, 11215, 11230, 11260, 11290, 11305,
            11320,
            ...
            48840, 48850, 48860, 48870, 48880, 48890, 49110, 49130, 49710,
            49720],
           dtype='int64', name='시군구지역코드', length=257)

In [358]:
len(local_code['시군구지역코드'])

253

In [461]:
# 방법1 함수 돌리기 
def location(diz_m):
    tmp = []
    for n in range(len(local_code)):
        for m in range(len(diz_m.columns.levels[1])):
            if local_code['시군구지역코드'][n] == diz_m.columns.levels[1][m]:
                tmp.append(local_code['지역명'][n])
            else :
                continue
    return tmp

In [373]:
#tmp_name_list  = cold_name.columns.levels[1].apply( lambda x: if x local_code['시군구지역코드'])

pandas.core.indexes.numeric.Int64Index

In [408]:
len(tmp), len(cold_name.columns.levels[1])

(253, 257)

# 로컬코드와 cold의 행수 불일치 문제 확인

In [390]:
right = []
for n in range(len(local_code)):
    right.append(local_code['시군구지역코드'][n])

In [391]:
left = []
for m in range(len(cold_name.columns.levels[1])):
    left.append(cold_name.columns.levels[1][m])

In [393]:
type(right),type(left)

(list, list)

In [401]:
right=pd.DataFrame(right)
left =pd.DataFrame(left)

In [411]:
right['v_r']=1
left['v_l']=1

In [414]:
right = right.set_index(0)
left = left.set_index(0)

In [426]:
r_l =pd.concat( [left,right], sort=True, axis=1)

In [450]:
r_l.loc[ r_l['v_r'] != 1, :]

       v_l  v_r
0
43710    1  NaN
44730    1  NaN
49710    1  NaN
49720    1  NaN

In [197]:
# 날짜 칼럼의 형식을 datetime으로 
# 방법1
#colde_sigun['날짜'] = cold_sigun['날짜'].apply( lambda x: pd.to_datetime(str(x), format='%Y%m%d' ))
# 방법2 <-더 빠른느낌
#cold_sigun.날짜= pd.to_datetime(cold_sigun.날짜, format='%Y%m%d')